#ifndef __PIN_ASSIGNMENT_H_
#define __PIN_ASSIGNMENT_H_

#include "WProgram.h"
#include <usb_keyboard.h>

#define NUM_LED  0
#define CAP_LED 12

// keyboard drives thru cols and reads thru rows
#define PIN_R11  1
int ROWS[] = { 25, 24,  9,  8,  7,  6,  5,  4,  3,  2 };
int COLS[] = { 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 };

uint16_t key_matrix[10][10] = {
	{ KEY_PAGE_DOWN, KEY_PAGE_UP, KEY_ESC, KEY_INSERT, KEY_HOME,
		KEY_END, KEY_RIGHT, KEY_DOWN, KEY_LEFT, KEY_UP },
	{ KEY_CAPS_LOCK, KEY_LEFT_SHIFT, KEY_LEFT_CTRL, KEY_LEFT_ALT,
		KEY_LEFT_GUI, KEY_RIGHT_GUI, KEY_RIGHT_ALT, KEY_RIGHT_CTRL,
		KEY_NON_US_BS, KEY_RIGHT_SHIFT},
	{ KEY_TAB, KEY_TILDE, KEY_A, KEY_Z, KEY_X, KEY_SPACE, KEY_COMMA,
		KEY_PERIOD, KEY_SLASH, KEY_ENTER },
	{ KEY_BACKSLASH, KEY_Q, KEY_S, KEY_D, KEY_C,
		KEY_V, KEY_M, KEY_L, KEY_SEMICOLON, KEY_QUOTE },
	{ KEY_F4, KEY_1, KEY_W, KEY_E, KEY_F,
		KEY_B, KEY_N, KEY_K, KEY_LEFT_BRACE, KEY_RIGHT_BRACE },
	{ KEY_F5, KEY_2, KEY_3, KEY_R, KEY_G,
		KEY_H, KEY_J, KEY_P, KEY_EQUAL, KEY_BACKSPACE },
	{ KEY_F6, KEY_4, KEY_5, KEY_T, KEY_Y,
		KEY_U, KEY_I, KEY_O, KEY_MINUS, KEY_F12 },
	{ KEY_F7, KEY_F8, KEY_6, KEY_7, KEY_F9,
		KEY_8, KEY_9, KEY_F10, KEY_0, KEY_F11 },
	{ KEY_F2, KEY_F3, KEYPAD_MINUS, KEYPAD_PLUS, KEYPAD_ENTER,
		KEYPAD_SLASH, KEYPAD_8, KEYPAD_5, KEYPAD_2, KEYPAD_0 },
	{ KEYPAD_ASTERIX, KEYPAD_9, KEYPAD_6, KEYPAD_3, KEYPAD_PERIOD,
		KEY_F1, KEY_NUM_LOCK, KEYPAD_7, KEYPAD_4, KEYPAD_1}
};

#endif // __PIN_ASSIGNMENT_H_
